# config/model/autoformer.yaml
_target_: "train.AutoformerConfig"
name: 'autoformer'

# label_len 必须小于pred_len
# 注意autoformer非常适合长序列预测
seq_len: 720
pred_len: 360
label_len: 180
d_model: 32
n_heads: 8
d_ff: 512
dropout: 0.2
activation: "gelu"
e_layers: 3
d_layers: 2
moving_avg: 175
c_out: 1
enc_in: 7
factor: 1

