# config/model/autoformer.yaml
_target_: "train.AutoformerConfig"
name: 'autoformer'

# label_len 必须小于pred_len
# 注意autoformer非常适合长序列预测
seq_len: 720
pred_len: 360
label_len: 180
d_model: 512
n_heads: 8
d_ff: 1024
dropout: 0.1
activation: "gelu"
e_layers: 4
d_layers: 1
moving_avg: 25
c_out: 1
enc_in: 7
factor: 5

