# config/model/autoformer.yaml
_target_: "train.AutoformerConfig"
name: 'autoformer'

# label_len 必须小于pred_len
# 注意autoformer非常适合长序列预测
seq_len: 230
pred_len: 100
label_len: 50
d_model: 512
n_heads: 8
d_ff: 2048
dropout: 0.2
activation: "gelu"
e_layers: 3
d_layers: 2
moving_avg: 25
c_out: 1
enc_in: 7
factor: 1

