_target_: "train.InformerConfig"
name: 'informer'
enc_in: 7
dec_in: 7
c_out: 1
seq_len: 720
pred_len: 360
label_len: 180
d_model: 64
n_heads: 8
e_layers: 4
d_layers: 1
d_ff: 1024
dropout: 0.2
factor: 1
attn: "prob"
activation: 'gelu'