_target_: "train.InformerConfig"
name: 'informer'
enc_in: 7
dec_in: 7
c_out: 1
seq_len: 230
pred_len: 100
label_len: 10
d_model: 512
n_heads: 8
e_layers: 3
d_layers: 1
d_ff: 2048
dropout: 0.2
factor: 1
attn: 'prob'
activation: 'gelu'