_target_: "train.InformerConfig"
name: 'informer'
enc_in: 7
dec_in: 7
c_out: 1
seq_len: 100
pred_len: 5
label_len: 2
d_model: 256
n_heads: 8
e_layers: 3
d_layers: 2
d_ff: 1024
dropout: 0.1
factor: 1
attn: "prob"
activation: "gelu"