_target_: "train.ReformerConfig"
name: 'reformer'
enc_in: 7
d_model: 256
dropout: 0.1
e_layers: 3
n_heads: 8
bucket_size: 16
n_hashes: 4
d_ff: 1024
c_out: 1
activation: 'gelu'
pred_len: 360
seq_len: 720
label_len: 180