_target_: "train.ReformerConfig"
name: 'reformer'
enc_in: 7
d_model: 512
dropout: 0.1
e_layers: 2
n_heads: 8
bucket_size: 8
n_hashes: 4
d_ff: 2048
c_out: 1
activation: 'gelu'
pred_len: 50
seq_len: 230
label_len: 25