version_base: 1.3

defaults:
  - _self_
  - model: informer

data:
  csv_file: "./data/更张.csv"
  batch_size: 16
  train_split: 0.99
  shuffle: True
  num_workers: 4

train:
  is_train: False
  epochs: 200        # 训练轮数
  learning_rate: 1e-3
  step_size: 20       # 学习率调度的步长
  gamma: 0.5          # 学习率衰减因子
  draw_loss: 10   # 保存模型的轮数间隔

path:
  load_dir: './outputs/2024-07-25/15-32-21/best_model.pth'

eval:
  not_roll: True





