version_base: 1.3


# 选择模型, manba目前有bug
defaults:
  - _self_
  - model: autoformer

data:
  csv_file: "./data/巴河桥.csv"
  batch_size: 16
  train_split: 0.99
  shuffle: True
  num_workers: 4

train:
  is_train: True
  epochs: 100        # 训练轮数
  learning_rate: 1e-3
  step_size: 15       # 学习率调度的步长
  gamma: 0.5          # 学习率衰减因子
  draw_loss: 10   # 保存模型的轮数间隔

path:
  load_dir:

eval:
  not_roll: True





