version_base: 1.3

defaults:
  - _self_
  - model: lstm

data:
  csv_file: "./data/巴河桥.csv"
  batch_size: 16
  train_split: 0.9
  shuffle: True
  num_workers: 4

train:
  is_train: True
  load_dir:
  epochs: 150        # 训练轮数
  learning_rate: 1e-3
  step_size: 10       # 学习率调度的步长
  gamma: 0.5          # 学习率衰减因子
  save_interval: 10   # 保存模型的轮数间隔







