version_base: 1.3

defaults:
  - _self_
  - model: lstm

data:
  csv_file: "./data/更张.csv"
  seq_len: 100
  pred_len: 1
  label_len: 50
  batch_size: 16
  train_split: 0.9
  shuffle: True

train:
  load_dir: "./outputs/2024-07-22/18-44-10/best_model.pth"
  epochs: 150        # 训练轮数
  learning_rate: 1e-3
  step_size: 15       # 学习率调度的步长
  gamma: 0.6          # 学习率衰减因子
  save_interval: 10   # 保存模型的轮数间隔







