version_base: 1.3


# 选择模型, manba目前有bug
defaults:
  - _self_
  - model: dlinear

data:
  csv_file: "./data/更张.csv"
  batch_size: 16
  train_split: 0.99
  shuffle: True
  num_workers: 4

train:
  is_train: True
  epochs: 120        # 训练轮数
  learning_rate: 5e-4
  step_size: 15       # 学习率调度的步长
  gamma: 0.5          # 学习率衰减因子
  draw_loss: 10   # 保存模型的轮数间隔

path:
  load_dir: "./outputs/2024-07-31/15-05-36/best_model.pth"

eval:
  not_roll: True





